In [12]:
## Create a 3x3 Array with values ranging between 2,10

In [1]:
import numpy as np
original_array=np.arange(2,11)
print(f"original array :{original_array}")
print(f"3d array :\n {original_array.reshape(3,3)}")


original array :[ 2  3  4  5  6  7  8  9 10]
3d array :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
