In [ ]:
## List And Tuple Converted to Array

In [10]:
import numpy as np
original_list=[1,2,3,5,4]
original_tuple=(8, 4, 6, 1, 2, 3)

list_to_array=np.array(original_list)
print(list_to_array)

tuple_to_array=np.array(original_tuple)
tuple_to_array=np.reshape(tuple_to_array,(2,3))

print(tuple_to_array)


[1 2 3 5 4]
[[8 4 6]
 [1 2 3]]
